Rookout/piper

- go.mod
- go.sum
- pkg/workflow-handler/workflows.go
- pkg/workflow-handler/workflows_utils.go
- pkg/workflow-handler/workflows_utils_test.go
> Feature: UT | Add test to AddFilesToTemplates

- workflows.values.yaml
> fix nginx ingress route

- pkg/git/github_utils_test.go
> Fix: Improve UT to IsOrgWebhookEnabled

- cmd/piper/piper.go
- docs/usage.md
- go.mod
- go.sum
- helm-chart/templates/deployment.yaml
- helm-chart/values.yaml
- pkg/conf/workflows_config.go
- pkg/utils/main.go
- pkg/utils/os_test.go
- pkg/webhook-hanlder/webhook_handler.go
- pkg/workflow-handler/workflows.go
- pkg/workflow-handler/workflows_utils.go
> Fix: edge cases with nil pointer dereferences

- examples/workflow.yaml
- pkg/server/routes/webhook.go
- pkg/webhook-handler/types.go
- pkg/webhook-handler/webhook_handler.go
> fix: typo in package name

- pkg/conf/rookout.go
> fix: rookout default value fix

- cmd/piper/piper.go
- makefile
- pkg/git/github_utils.go
- pkg/git/test_utils.go
- pkg/server/server.go
- pkg/workflow-handler/workflows.go
- pkg/workflow-handler/workflows_utils.go
> fix: linting issues

- helm-chart/values.yaml
> fix: minor chart fix

- makefile
> fix: move chart path

- .github/workflows/release.yaml
> fix: change chart deployment flow

- .github/workflows/release.yaml
- helm-chart/Chart.yaml
- helm-chart/README.md
- helm-chart/values.yaml
> feat: add app version to helm chart

- helm-chart/templates/deployment.yaml
- pkg/conf/workflows_config.go
> fix: blank config map support

- .github/workflows/ci.yaml
- makefile
- scripts/init-argo-workflows.sh
- scripts/init-kind.sh
- scripts/init-nginx.sh
- scripts/init-piper.sh
- fix: add e2e test
- fix: add e2e test
- fix: add e2e test
- fix: makefile improvence
> fix: makefile improvence - RK-19036

- pkg/server/server.go
> fix: stop healthz logs spam - RK-19035

- pkg/conf/workflow_server.go
> fix: remove argo configuration requirements - RK-19033

- pkg/conf/workflows_config.go
- pkg/utils/common.go
- pkg/utils/common_test.go
- pkg/workflow_handler/workflows_utils.go
- pkg/workflow_handler/workflows_utils_test.go
> fix: json yaml conflic umarshling template ref to DAG task - RK-19034

- .github/workflows/snyk.yaml
> fix: add snyk scan - RK-19072

- .github/workflows/lint-commit.yaml
- .github/workflows/lint-pr.yaml
> feat: change commit linter - RK-19094

- cmd/piper/piper.go
- pkg/git_provider/github.go
- pkg/git_provider/types.go
- pkg/server/server.go
- pkg/webhook_handler/webhook_handler_test.go
> feat: add gracefull shutdown - RK-19184 

- docs/usage.md
- pkg/git_provider/github.go
- pkg/workflow_handler/workflows.go
> fix: global parameters added and reorganized - RK-19161 

- docs/usage/global_variables.md
- pkg/git_provider/github.go
- pkg/git_provider/types.go
- pkg/workflow_handler/workflows.go
> fix: add labels as comma seprated list in global parameters - RK-19217 

- .github/workflows/e2e.yaml
> ci: e2e queue - RK-19272 

- pkg/git_provider/github.go
> fix: pull request url to html url - RK-19264 

- pkg/event_handler/main.go
- pkg/webhook_handler/webhook_handler.go
> fix: retry and resumbit notifiction fix - RK-19261 

- .github/workflows/release.yaml
> ci: arm64 support for images - RK-19338 

- .github/workflows/release.yaml
This PR will add labels to the docker image created.
> ci: add labels to image release - RK-19485 
